/* ============ EPILOGHI PERSONALI E IMPRESE (achievement) ============ */

/* Epiloghi per persona, per tipo di finale:
   'alba'    = patto rotto, tutti liberi (e_alba, e anche e_ospiti mostra i suoi)
   'custode' = uno di voi è rimasto al Belvedere (e_custode)
   'penna'   = Gregorio ha spezzato la penna: il ciclo è CHIUSO (e_penna)
   'smemorati' = la notte è stata PAGATA con la memoria (e_smemorati)           */

const HERO_EPILOGUES = {

  gaetano: {
    alba: `Gaetano ha passato i primi tre giorni a casa a scrivere una relazione tecnica di quarantadue pagine intitolata "Anomalie ottiche e termodinamiche osservate presso struttura ricettiva irpina", che non ha mai inviato a nessuno. L'ha stampata, rilegata e messa nella libreria, tra le tesi di laurea. Ogni tanto la apre, la sfoglia, la richiude. Ha aggiunto una sola nota a mano in copertina: "Verificato empiricamente. Non ripetere l'esperimento." Ai colleghi che gli chiedono della vacanza risponde: "Bella. Strutturalmente interessante." E quando un satellite passa sopra l'Irpinia, se può, gli fa fare una foto in più.`,
    custode: `Gaetano ha rifatto i calcoli cento volte: le probabilità, i rischi, le alternative. Il risultato è sempre lo stesso, e non lo consola mai. È lui che organizza il viaggio di agosto, ogni anno, con precisione militare: partenza alle 15:00, arrivo entro il tramonto, "perché i tornanti di notte no". È lui che porta i pezzi di ricambio per tutto ciò che al Belvedere può rompersi, e li monta in silenzio, e il custode lo guarda lavorare dalla soglia con un sorriso che non invecchia. Nessuno dei due dice niente. Gli ingegneri e i custodi si capiscono così: a manutenzione.`,
    penna: `Gaetano è tornato ad agosto con il contachilometri azzerato apposta, e ha rifatto la strada: ventisei tornanti in discesa, 11,4 chilometri, dislivello coerente, benzina consumata NORMALE. Al tornante undici si è fermato, è sceso, ha guardato la valle per dieci minuti. Poi ha scritto l'ultima riga della relazione tecnica, quella che aspettava da un anno: "Anomalia risolta alla radice. Metodo: umanistico." È l'unica volta, in tutta la sua carriera, che ha firmato un documento tecnico con la stilografica. Una qualsiasi. Comprata nuova. Che scrive e basta.`,
    smemorati: `Gaetano ha trovato nel telefono una nota di quella notte, ore 4:12, scritta da lui: "NON RIPETERE L'ESPERIMENTO." Nessun contesto. Nessun ricordo. Ha passato una settimana a cercare di ricostruire l'esperimento con il rigore che metterebbe in un'indagine su un satellite perso — e niente, il buco è pulito, professionale, IRRECUPERABILE. Da allora misura tutto due volte e non sa perché. E quando in autostrada passa l'uscita di Avellino, le mani gli si stringono sul volante da sole. Claudia, dal sedile del passeggero, gli appoggia la mano sul braccio: "Tira dritto." Non sa perché lo dice. Lui non sa perché obbedisce. Tirano dritto.`,
  },

  natalino: {
    alba: `Natalino è tornato al salone il martedì, e alla prima cliente che gli ha chiesto "novità?" ha risposto con la storia COMPLETA, senza omettere niente: le bambole, lo Chef, il pozzo che parla. La cliente ha riso per quaranta minuti e ha lasciato il triplo di mancia. Da allora è il suo numero: la racconta a puntate, un tornante a settimana, e c'è gente che prenota la piega SOLO per sentire il seguito. Le forbici professionali giapponesi sono tornate nella custodia, in vetrina, con una targhetta nuova: "In pensione. Con onore." E se gli chiedete se è tutto vero, alza le mani: "Amore mio, IO faccio i capelli. La storia si è fatta da sola."`,
    custode: `Natalino sale al Belvedere anche fuori stagione, "perché i capelli non conoscono calendario". Ha piazzato una poltrona da barbiere professionale nella dependance — l'ha portata su a pezzi, in tre viaggi, bestemmiando a ogni tornante — e una volta al mese fa il taglio a tutti: al custode, a Gregorio, e una spuntatina simbolica ai salici, "che si erano lasciati andare". È l'unico che nel salone del Belvedere parla ad alta voce, ride forte, mette la musica. La casa lo lascia fare. La casa, sospettano tutti, lo ASPETTA.`,
    penna: `Natalino ha chiesto — e OTTENUTO — una scheggia della penna spezzata. La tiene in vetrina al salone, montata su un piedistallo minuscolo, con un cartellino scritto a mano: "Ha firmato per 125 anni. Ha smesso." Le clienti pensano sia arte moderna. Lui lascia credere. Solo a quelle speciali — quelle che arrivano con lo sguardo di chi ha dormito male in una casa che non era d'accordo — racconta la storia vera, a bassa voce, tra un colpo di forbice e l'altro. E alla fine aggiunge sempre: "Il trucco non è vincere, amore mio. Il trucco è convincere chi tiene la penna."`,
    smemorati: `Natalino ha trovato le forbici professionali giapponesi in vetrina, montate su un piedistallo, con un cartellino scritto nella SUA grafia: "In pensione. Con onore." Non ricorda di avercele messe. Non ricorda il perché. Le ha lasciate lì — "se l'ho scritto io, un motivo c'era, e mi fido di me" — e ha comprato un paio nuovo. Alle clienti racconta che la vacanza in Irpinia è stata "bellissima, piscina da sogno, torniamo l'anno prossimo". Lo dice col sorriso. Però ogni volta che in un negozio parte un carillon, abbassa la voce a metà frase. E non se ne accorge nemmeno.`,
  },

  claudia: {
    alba: `Claudia ha ottantasette foto di quella notte e non ne ha pubblicata nemmeno una. Le tiene in un album privato che si chiama "NO", e lo apre solo quando qualcuno al lavoro dice che "l'engagement è tutto". La foto del riflesso sbagliato — quella con la luna rossa nell'acqua e la luna sottile nel cielo — l'ha stampata e messa in un cassetto, a faccia in giù. Ha ripreso a lavorare coi social del colosso degli occhiali, ma ha sviluppato una specialità nuova che in azienda nessuno le ha insegnato: capire al primo sguardo quando un'immagine MENTE. La pagano il doppio, adesso. Non sanno il perché. Lei sì.`,
    custode: `Claudia cura — da lontano, e senza farsi pagare — la comunicazione del Belvedere: due post a settimana, tono caldo, luce dorata. È brava al punto che il relais è pieno tutto l'anno, e nessun ospite ha mai notato niente. Solo lei sa che in ogni foto che pubblica c'è, da qualche parte, un dettaglio che non torna: un'ombra in più, un riflesso storto, una finestra accesa che non dovrebbe. Li lascia apposta. È il suo modo di dire la verità senza dirla: chi deve capire, capirà. Il custode, ogni volta, mette like per primo.`,
    penna: `Claudia, per la prima volta in dieci anni di mestiere, ha pubblicato una foto senza pensarci: la villa nel primo sole, vuota, mortale, bellissima, con la polvere di Gregorio ancora sospesa nell'aria come un controluce. Nessuna caption. Nessun hashtag. Nessun tag. È diventato il suo post più condiviso di sempre, e lei non ha mai risposto a un solo commento. Quando il direttore marketing le ha chiesto "qual era la strategia?", ha risposto la verità: "Nessuna. È l'unica foto che ho fatto CHIEDENDO PERMESSO." Nessuno ha capito. Va benissimo così.`,
    smemorati: `A Claudia mancano ottantasette foto. Se ne è accorta subito, ovviamente — la numerazione del rullino salta, il buco è preciso come un taglio — e ha trovato nel telefono un album vuoto, creato quella notte, intitolato "NO". Non ricorda di averlo fatto. Non l'ha cancellato. Ha passato la carriera a costruire immagini, e sa riconoscere il lavoro di una professionista: quel vuoto è CURATO. Qualcuno — lei — ha deciso che ottantasette immagini non dovevano esistere, e si fida della collega. Solo una cosa è rimasta: quando inquadra una piscina di sera, il dito esita sul tasto. Un secondo. Poi scatta comunque. Quasi sempre.`,
  },

  federico: {
    alba: `Federico ha aspettato tre mesi — "il tempo tecnico del lutto professionale" — e poi ha fatto la cosa che tutti temevano: è tornato su a proporre a Gregorio un piano di rilancio. Stavolta con un contratto VERO, letto riga per riga da tutti e cinque, con Gaetano che controllava le clausole e Natalino che controllava Gaetano. Il "Relais Belvedere — da Gregorio e Ada" è oggi il suo cliente migliore e l'unico di cui non parla mai nei casi studio. Quando gli chiedono perché, risponde con l'unica frase umile del suo repertorio: "Certi successi si festeggiano in silenzio." Poi però il fatturato lo mostra lo stesso.`,
    custode: `Federico non si è mai perdonato la prenotazione — "cinque stelle, ragazzi, un AFFARE" — e ha risolto come risolve tutto: lavorando il doppio. È lui che gestisce ogni dettaglio dei ritorni di agosto, lui che tiene i rapporti col paese, lui che ha convinto il comune di Pietrafonda a rifare la strada dei tornanti "per motivi turistici". Ogni anno, all'arrivo, consegna al custode un report rilegato: presenze, recensioni, progetti. Il custode lo sfoglia con finta attenzione e poi lo abbraccia, e Federico ogni volta dice "dai, che è un lavoro come un altro", e ogni volta non gli esce bene.`,
    penna: `Federico ha comprato la villa. OVVIAMENTE Federico ha comprato la villa — "era un affare, ragazzi, un AFFARE VERO stavolta" — ed è l'unico immobile della sua vita che ha pagato senza trattare di un euro. L'ha intestata a una cooperativa di Pietrafonda: il bar di Peppe fa il catering, Don Michele benedice le stagioni "male e a festa", e il regolamento interno, scritto da Federico personalmente, ha un solo articolo in grassetto: "Il registro degli ospiti si firma ALL'USCITA. Se vi è piaciuto."`,
    smemorati: `Federico ha trovato nel cassetto la stampa di una prenotazione — "Relais Belvedere, 5 ospiti, weekend" — con una nota a margine nella sua grafia: "MAI PIÙ ANTICIPI." Non ricorda il weekend. Non ricorda la nota. Il conto in banca conferma l'anticipo, e questo lo tormenta più di tutto: Federico DIMENTICA i weekend, può succedere, ma Federico non dimentica un ANTICIPO. Da allora legge ogni contratto due volte, anche i moduli della palestra. E ai clienti che hanno fretta di firmare dice sempre la stessa frase, che non sa da dove gli venga e che gli esce con una convinzione che lo spaventa: "Domattina. Con calma."`,
  },

  emanuela: {
    alba: `Emanuela ha rimesso il kit nella borsa, la borsa nell'armadio, e per due settimane non ha voluto sentir parlare di montagna. Poi, piano piano, le cose sono tornate al loro posto: il salone, le clienti, i pettegolezzi con Natalino tra un taglio e l'altro — che adesso hanno un capitolo segreto che le clienti non sentiranno mai. Nella borsa, però, c'è una cosa nuova: un mazzetto di erbe argentate, seccate, legate con lo spago. "Contro il freddo", dice se qualcuno chiede. Non specifica QUALE freddo. E quando una cliente arriva con le mani gelate e lo sguardo di chi ha visto qualcosa che non racconta, Emanuela le prepara una tisana senza chiedere niente. Certe ricette si tramandano così.`,
    custode: `Emanuela ha preso in mano la cosa come prende in mano tutto: praticamente. Ha piantato l'orto nuovo con le sue mani, ampliando quello di Ada — "le erbe vanno rinnovate, non discutere" — e ha lasciato al Belvedere un kit di pronto soccorso in ogni stanza, controllati e riforniti a ogni visita. Il custode dice che non servono. Lei li rifornisce lo stesso. L'ultima domenica di agosto, prima di ripartire, prepara sempre una teglia di parmigiana "per il viaggio" e la lascia in cucina, sapendo benissimo che il custode non mangia. La teglia, ogni anno, torna vuota e lavata. Nessuno dei due ha mai commentato.`,
    penna: `Emanuela ha trapiantato l'orto di Ada a Pietrafonda, aiuola per aiuola, nel terreno dietro la canonica — "le erbe non si abbandonano, non discutere". Le erbe argentate hanno attecchito al primo colpo, cosa che il vivaista della valle definisce "botanicamente offensiva". Ora ogni giovedì, giorno di mercato, c'è un banchetto piccolo con tisane e mazzetti legati a spago, e un cartello scritto col pennarello: "Contro il freddo. Quale freddo? Nessuno. FINALMENTE." I soldi vanno alla cooperativa della villa. Il primo mazzetto di ogni raccolto, però, lo porta lei al pozzo. Per una che ha ancora le mani fredde.`,
    smemorati: `Emanuela ha trovato nella borsa un mazzetto di erbe argentate legate a spago. Non ricorda di averle raccolte, non riconosce la specie, e il vivaista di fiducia nemmeno. Le ha tenute. Quando seccano troppo, le rinnova con altre erbe simili, "per abitudine" — un'abitudine che non ricorda di aver preso. E una sera d'agosto, ogni anno, sempre la stessa, prepara la tisana senza contare le tazze: ne vengono fuori cinque. A tavola sono in cinque. I conti tornano, dice lei. E se mentre versa le viene da mormorare "contro il freddo"... be', è agosto, fa caldo, e nessuno le chiede mai QUALE freddo.`,
  },

};

/* ---------- IMPRESE — achievement di fine partita ---------- */
/* Ogni voce: { flag, icon, title, desc } — sbloccata se G.flags[flag] è veritiero. */

const IMPRESE = [
  { flag: 'visto_giardiniere',   icon: '🌳', title: 'Le Siepi Ricambiano',        desc: 'Avete notato il lavoro del Giardiniere già dal viale d\'ingresso.' },
  { flag: 'visto_registro',      icon: '📖', title: 'Lettori del Venticinquennio', desc: 'Avete sfogliato il registro all\'indietro PRIMA di firmare. 1999, 1974, 1949...' },
  { flag: 'firma_rinviata',      icon: '🖋', title: 'Domattina, Con Calma',        desc: 'Avete rimandato la firma. Il Belvedere non se l\'aspettava.' },
  { flag: 'visto_pozzo',         icon: '🪣', title: 'La Corda Tesa',               desc: 'Natalino ha aperto le tende della Camera del Pozzo. Ovviamente.' },
  { flag: 'battuta_1899',        icon: '🍷', title: '"Astemio dal 1899"',          desc: 'Avete costretto Gregorio al brindisi. Era CHIARAMENTE una battuta.' },
  { flag: 'sesto_ospite',        icon: '🥽', title: 'Il Sesto Accappatoio',        desc: 'Avete ispezionato l\'accappatoio senza iniziale. E gli occhiali del \'99.' },
  { flag: 'vista_finestra',      icon: '🔬', title: 'Metodo Scientifico',          desc: 'Gaetano ha sacrificato un\'infradito alla scienza. Era nuova.' },
  { flag: 'tentata_fuga',        icon: '🚗', title: 'In Accappatoio nel Bosco',    desc: 'Avete provato a scappare in piena notte. Il cancello aveva altri piani.' },
  { flag: 'storia_ada',          icon: '🕯', title: 'L\'Ultima Domanda',           desc: 'Avete trattenuto Gregorio: ogni verità gli è costata una ciocca bianca.' },
  { flag: 'voce_sofia',          icon: '🍾', title: 'Il Sussurro di Sofia',        desc: 'Avete ascoltato una bottiglia del 1999. Non lo dimenticherete.' },
  { flag: 'chef_amico',          icon: '👨‍🍳', title: 'Il Ricordo d\'Affetto',       desc: 'Avete commosso lo Chef con una ciocca tagliata ad arte. Nessun sangue.' },
  { flag: 'nodo_cantina',        icon: '🧂', title: 'Il Sale Fedele',              desc: 'Nodo della cantina sciolto: sale del 1899 e bottiglia del Padrone.' },
  { flag: 'medaglione',          icon: '💍', title: 'Il Valzer delle Bambole',     desc: 'Avete recuperato il medaglione di Ada dalla stanza del 1924.' },
  { flag: 'nodo_piano',          icon: '🚪', title: 'I Ricordi della Casa',        desc: 'Nodo del piano proibito sciolto: il diario di Ada è vostro.' },
  { flag: 'avvertimento_specchio', icon: '🪞', title: 'Lo Specchio Velato',        desc: 'Avete guardato il Banchetto apparecchiato per voi. E avete scelto di no.' },
  { flag: 'nodo_pozzo',          icon: '💧', title: 'L\'Acqua che Ricorda',        desc: 'Nodo del pozzo sciolto: Ada vi ha dato la sua acqua.' },
  { flag: 'ada_alleata',         icon: '👗', title: 'Il Nome Restituito',          desc: 'Avete ridato ad Ada il suo nome. Il pozzo non conta più le notti.' },
  { flag: 'pagine_diario',       icon: '📜', title: 'Chi Scende nel Pozzo',        desc: 'Qualcuno si è calato DAVVERO. Le tre pagine strappate sono vostre.' },
  { flag: 'gregorio_umano',      icon: '🥂', title: 'Il Ritorno del Padrone di Casa', desc: 'Gregorio è tornato uomo — col vino del 1899 nel bicchiere, o con le parole di Ada nelle orecchie.' },
  { flag: 'casa_vacilla',        icon: '📊', title: 'Il Pitch al Patto',           desc: 'Federico ha fatto una proposta commerciale a una casa affamata. E ha quasi chiuso.' },
  { flag: 'rituale_fatto',       icon: '🧂', title: 'Sale, Acqua e un Nome',       desc: 'Avete compiuto il rituale di Ada sulla firma. La casa lo ricorderà.' },
  { flag: 'fame_sconfitta',      icon: '🍽', title: 'Il Tovagliolo Piegato',       desc: 'Avete sconfitto la Fame. Il pasto è finito. Per sempre.' },
  { flag: 'finale_custode',      icon: '🗝', title: 'Il Nuovo Custode',            desc: 'Uno di voi è rimasto. Il finale di cui non parlerete mai più.' },
  { flag: 'finale_ospiti',       icon: '🖼', title: 'Il Ritratto Più Bello',       desc: 'Vi siete seduti al Banchetto. Il Belvedere ringrazia per la posa.' },
  { flag: 'pista_paese',         icon: '⛪', title: 'Il Sesto del Settantaquattro', desc: 'Siete scesi a Pietrafonda senza firma addosso, e siete TORNATI dentro.' },
  { flag: 'visto_bar_1999',      icon: '☕', title: 'Cinque Caffè, Offre Peppe',    desc: 'Avete letto il conto mai battuto del bar. E la consolazione di Ada.' },
  { flag: 'segreto_custodi',     icon: '📚', title: 'Più Vecchio di Gregorio',      desc: 'I registri parrocchiali: il patto cambia custode ogni 25 anni. Da SEMPRE.' },
  { flag: 'vespri_suonati',      icon: '🔔', title: 'I Vespri del Belvedere',       desc: 'Avete suonato la campanella di Don Michele davanti alla Fame. Ada ha risposto.' },
  { flag: 'finale_smemorati',    icon: '🫙', title: 'La Vacanza Qualunque',         desc: 'Avete pagato con la memoria della notte. Vittoria. Di chi, non lo ricordate.' },
  { flag: 'strada_che_torna',    icon: '🛣', title: 'Il Tornante Undici',           desc: 'Avete visto la strada tornare — e siete rientrati con la risposta in tasca.' },
  { flag: 'giardiniere_potato',  icon: '🌾', title: 'Potatura Straordinaria',       desc: 'Il Giardiniere è paglia sparsa nei filari. Il turno di notte è scoperto.' },
  { flag: 'biglietto_strappato', icon: '🎫', title: 'Ritenta',                      desc: 'L\'ultimo Gratta e Vinci aveva vinto "per sempre". Strappato in due, in faccia al banco.' },
  { flag: 'casa_rispetta',       icon: '⚖', title: 'Vizio del Consenso',           desc: 'Avete denunciato la trappola al maggiordomo. Il sorriso è scivolato di un millimetro.' },
  { flag: 'cucina_in_sciopero',  icon: '🍳', title: 'La Cucina Sciopera',           desc: 'Lo Chef dalla vostra parte del tavolo, i camerieri rientrati nelle pareti.' },
  { flag: 'cerchio_di_porcellana', icon: '🧸', title: 'Il Recinto delle Signorine', desc: 'Trentadue bambole sonnambule in cerchio tra voi e la Fame.' },
  { flag: 'paese_sa',            icon: '🚌', title: 'La Corriera del \'74',        desc: 'Gennaro guidò quaranta minuti in discesa a chilometraggio zero. Il paese lo sa dal 1899.' },
  { flag: 'finale_penna',        icon: '🖋', title: 'La Penna Spezzata',            desc: 'Nessun custode nuovo. Nessun custode vecchio. Un finale fuori registro.' },
  { flag: 'tronello_promesso',   icon: '🌿', title: 'Manutenzione',                 desc: 'Natalino ha condiviso il tronello con un fantasma. E gli è sembrato EDUCATO così.' },
  { flag: 'ada_ride',            icon: '😄', title: 'La Risata che Costa',          desc: 'Ada ha riso, dopo cinquant\'anni. L\'ha pagata volentieri.' },
  { flag: 'fumata_di_gruppo',    icon: '🌿', title: 'Il Cerchio del Balcone',       desc: 'Dieci minuti di vacanza vera. E il fumo, in cambio, vi ha disegnato la mappa.' },
  { flag: 'intercapedine_trovata', icon: '📐', title: 'Ottanta Centimetri',         desc: 'La stanza era più corta dei suoi muri. Dietro la quinta cornice: il ritratto della casa.' },
  { flag: 'anello_reso',           icon: '💍', title: 'Per Sempre Qui',              desc: 'La piscina ha emesso una ricevuta, e voi l\'avete recapitata: a Sofia, 25 anni dopo.' },
];

/* ---------- CRONACHE DEL BELVEDERE ----------
   Righe di epilogo mondiale mostrate nel finale SOLO se il flag è attivo. */

const CRONACA = [
  { flag: 'chef_amico',       text: 'Lo Chef ha appeso la mannaia: ora impasta pane per il paese, ogni alba. Sul grembiule, ricamata da mani che conoscete, una ciocca di capelli.' },
  { flag: 'ada_alleata',      text: 'Il pozzo non conta più le notti: le tacche sulla pietra si stanno cancellando da sole, una per sera, come un debito che si estingue.' },
  { flag: 'voce_sofia',       text: 'La bottiglia "Sofia, 1999" è stata stappata in giardino, al sole. Il profumo — dicono — era di crema solare e di risate. Poi, più niente. Libera.' },
  { flag: 'ernesto_libero',   text: 'A una sorella molto anziana, in una casa di riposo di Avellino, è sembrato di sentire il fratello dire "grazie". Ha smesso di aspettare. Ha iniziato a ricordare.' },
  { flag: 'gregorio_umano',   text: 'Gregorio invecchia di un anno all\'anno, come tutti, e lo trova MERAVIGLIOSO: festeggia due compleanni al mese "per recuperare l\'arretrato".' },
  { flag: 'storia_1974',      text: 'Don Michele è salito al Belvedere, dopo cinquant\'anni. Ha spolverato lui la cornice di Aldo. Nessuno ha sentito cosa si sono detti, ma i vespri, quella sera, sono durati il doppio.' },
  { flag: 'pista_paese',      text: 'Pietrafonda riapre le persiane. Il bar "Da Peppe" ha riacceso la macchina del caffè: il nuovo gestore batte per primo un conto rimasto aperto dal 1999. Cinque caffè. Offerti.' },
  { flag: 'medaglione',       text: 'Il medaglione d\'argento è tornato al pozzo, dove le sei ciocche intrecciate riposano insieme. Ogni tanto, di notte, qualcuno canticchia. In sei.' },
  { flag: 'avvertimento_specchio', text: 'Lo specchio della camera del 1899 adesso riflette solo la stanza. Qualche ospite giura di vederci, ogni tanto, cinque figure che salutano. Sorridendo.' },
  { flag: 'giardiniere_potato', text: 'Lo spaventapasseri si è rifatto, com\'era inevitabile. Ma adesso sta nei filari a fare il suo mestiere: spaventa i corvi. Ai passanti notturni, dicono, si toglie il cappello.' },
  { flag: 'biglietto_strappato', text: 'Il tabaccaio di Baiano giura che un Gratta e Vinci strappato è ricomparso intero nel raccoglitore. Sul retro, in una grafia d\'altri tempi: "RITENTA TU."' },
  { flag: 'bambole_addormentate', text: 'Le trentadue signorine del 1924 dormono ancora, composte, le mani in grembo. Un restauratore le ha definite "pezzi unici in condizioni perfette". Nessuno osa svegliarle per venderle.' },
  { flag: 'paese_sa', text: 'La corriera azzurra è ripartita dal tornante undici con la benzina che aveva nel 1974. Alla guida, per l\'ultima tratta, un pensionato di nome Gennaro. In discesa. Cantando.' },
  { flag: 'fumata_di_gruppo', text: 'Sul balcone del primo piano, certe notti d\'estate, il fumo di chissà cosa sale dritto e poi si DISPONE — angoli retti, corridoi, stanze. I nuovi gestori l\'hanno visto. Hanno deciso, con saggezza irpina, di non farci domande.' },
  { flag: 'finale_penna', text: 'La stilografica spezzata riposa nella cripta di Pietrafonda, tra i registri parrocchiali, in una piccola teca. Il cartellino dice: "Non scrive più. Non deve."' },
  { flag: 'ada_ride', text: 'Dal pozzo del giardino, certe sere d\'estate, sale un profumo d\'erba bruciata e una risata di donna, giovane e fuori orario. Gli ospiti pensano a una festa in valle. Il giardiniere nuovo, che ne sa più di loro, lascia sempre una foglia di fico sul secchio.' },
];
